export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const VERIFICATION_NEEDED = 'VERIFICATION_NEEDED';
export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST';
export const VERIFICATION_SUCCESSFUL = 'VERIFICATION_SUCCESSFUL';
export const VERIFICATION_FAILED = 'VERIFICATION_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const CLOCKS_REQUEST = 'CLOCKS_REQUEST';
export const CLOCKS_REQUEST_SUCCEEDED = 'CLOCKS_REQUEST_SUCCEEDED';
export const CLOCKS_REQUEST_FAILED = 'CLOCKS_REQUEST_FAILED';
export const CLOCKS_RETRIEVED = 'CLOCKS_RETRIEVED';