export const AUTHENTICATION_CHECK_REQUEST = 'AUTHENTICATION_CHECK_REQUEST';
export const AUTHENTICATION_CHECK_SUCCESS = 'AUTHENTICATION_CHECK_REQUEST_SUCCESS';
export const AUTHENTICATION_CHECK_FAIL = 'AUTHENTICATION_CHECK_REQUEST_FAIL';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const VERIFICATION_NEEDED = 'VERIFICATION_NEEDED';
export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLOCKS_REQUEST = 'CLOCKS_REQUEST';
export const CLOCKS_REQUEST_SUCCESS = 'CLOCKS_REQUEST_SUCCESS';
export const CLOCKS_REQUEST_FAIL = 'CLOCKS_REQUEST_FAIL';

export const ADD_CLOCK_REQUEST = 'ADD_CLOCK_REQUEST';
export const ADD_CLOCK_REQUEST_SUCCESS = 'ADD_CLOCK_REQUEST_SUCCESS';
export const ADD_CLOCK_REQUEST_FAIL = 'ADD_CLOCK_REQUEST_FAIL';

export const REMOVE_CLOCK_REQUEST = 'REMOVE_CLOCK_REQUEST';
export const REMOVE_CLOCK_REQUEST_SUCCESS = 'REMOVE_CLOCK_REQUEST_SUCCESS';
export const REMOVE_CLOCK_REQUEST_FAIL = 'REMOVE_CLOCK_REQUEST_FAIL';